export const weatherEmoji = {
  0: "☀️",
  1: "🌤️",
  2: "⛅",
  3: "☁️",
  45: "🌫️",
  48: "🌫️",
  51: "🌦️",
  53: "🌦️",
  55: "🌧️",
  56: "🌧️",
  57: "🌧️",
  61: "🌧️",
  63: "🌧️",
  65: "🌧️",
  66: "🌧️",
  67: "🌧️",
  71: "🌨️",
  73: "🌨️",
  75: "❄️",
  77: "🌨️",
  80: "🌦️",
  81: "🌦️",
  82: "⛈️",
  85: "🌨️",
  86: "❄️",
  95: "⛈️",
  96: "⛈️",
  99: "⛈️",
};

export const cityMap = {
  // 한국
  서울: "Seoul",
  부산: "Busan",
  대구: "Daegu",
  인천: "Incheon",
  대전: "Daejeon",
  광주: "Gwangju",
  울산: "Ulsan",

  // 일본
  도쿄: "Tokyo",
  요코하마: "Yokohama",
  오사카: "Osaka",
  나고야: "Nagoya",
  삿포로: "Sapporo",
  후쿠오카: "Fukuoka",
  고베: "Kobe",
  교토: "Kyoto",
  가와사키: "Kawasaki",
  사이타마: "Saitama",
  히로시마: "Hiroshima",
  센다이: "Sendai",
  기타큐슈: "Kitakyushu",
  치바: "Chiba",
  사카이: "Sakai",
  니가타: "Niigata",
  하마마쓰: "Hamamatsu",
  구마모토: "Kumamoto",
  시즈오카: "Shizuoka",
  오카야마: "Okayama",

  // 일본 관광도시
  나라: "Nara",
  가나자와: "Kanazawa",
  나가사키: "Nagasaki",
  가고시마: "Kagoshima",
  마쓰야마: "Matsuyama",
  오이타: "Oita",
  나하: "Naha",
  아오모리: "Aomori",
  나가노: "Nagano",
  와카야마: "Wakayama",
  다카마쓰: "Takamatsu",
  고치: "Kochi",
  미야자키: "Miyazaki",
};
